# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "ialfzzyffpruxifznfhz"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL.
port = 54322

[studio]
# Port to use for Supabase Studio.
port = 54323
enabled = true