// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://bfveluzxxkrxwvlpelgx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdmVsdXp4eGtyeHd2bHBlbGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1NDk5MTYsImV4cCI6MjA0NzEyNTkxNn0.DV2fKcV7ecdwfg8BkepqChyh8ZLPk2MsbiPPPsE8XQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);