// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ialfzzyffpruxifznfhz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbGZ6enlmZnBydXhpZnpuZmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyOTQwODcsImV4cCI6MjA0Njg3MDA4N30.JtRU3ZimPQK06frPFNOMzBhFEubEKU1DA7uZfAPmp8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);