import { AIProvider } from '@/types/ai';

export const providers: AIProvider[] = [
  {
    name: 'GPT-4',
    capabilities: ['writing', 'coding', 'chat', 'math', 'reasoning', 'structured_output'],
    apiEndpoint: 'https://api.openai.com/v1/chat/completions',
    strengths: {
      writing: 9,
      coding: 8.5,
      chat: 9,
      math: 8.5,
      reasoning: 9,
      structured_output: 9,
    },
    costPerToken: 0.03,
    averageLatency: 2000,
    contextWindow: 8192,
    specialties: ['complex reasoning', 'creative writing', 'code generation'],
    features: {
      toolUse: true,
      codeInterpreter: true,
      structuredOutput: true,
      retrieval: false,
      functionCalling: true,
    },
    limitations: [
      'Limited context window compared to Claude',
      'Higher latency for complex tasks',
      'Inconsistent with mathematical calculations',
    ],
  },
  {
    name: 'Claude-3',
    capabilities: ['writing', 'coding', 'data_analysis', 'chat', 'math', 'reasoning', 'structured_output'],
    apiEndpoint: 'https://api.anthropic.com/v1/messages',
    strengths: {
      writing: 9.5,
      coding: 9,
      data_analysis: 9,
      chat: 9,
      math: 9,
      reasoning: 9.5,
      structured_output: 9.5,
    },
    costPerToken: 0.025,
    averageLatency: 1800,
    contextWindow: 200000,
    specialties: ['long-form content', 'analysis', 'academic writing'],
    features: {
      toolUse: true,
      codeInterpreter: true,
      structuredOutput: true,
      retrieval: true,
      functionCalling: true,
    },
    limitations: ['May be overly cautious with certain tasks', 'Higher cost than some alternatives'],
  },
  {
    name: 'Google-PaLM',
    capabilities: ['writing', 'coding', 'chat', 'math', 'structured_output'],
    apiEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models/text-bison-001',
    strengths: {
      writing: 8,
      coding: 8,
      chat: 8.5,
      math: 8.5,
      structured_output: 8.5,
    },
    costPerToken: 0.02,
    averageLatency: 1500,
    contextWindow: 8192,
    specialties: ['quick responses', 'general knowledge'],
    features: {
      toolUse: false,
      codeInterpreter: true,
      structuredOutput: true,
      retrieval: false,
      functionCalling: true,
    },
    limitations: ['Limited context window', 'Less consistent with complex tasks', 'Limited tool use capabilities'],
  },
];